### ISSUE TITLE
Request: Could you create releases please?

### ISSUE THREAD

**Issue by jamesla** [jpnewman/ansible-role-artifactory#4]
Hey thanks for making this role, could you make a release for this role please so that I can lock my requirements.yml down to a specific version?

**Comment by jpnewman** [comment]
Hi James, I've tag this role and its dependent roles 'jpnewman.java' and 'jpnewman.apache' with version 1.0.0.

FYI: I'll be updating this role shortly to fully support the MySQL database and will rev the version number.

**Comment by jamesla** [comment]
Thanks John that will let me lock the dependency down on my box. Greatly appreciated.
